DROP TABLE IF EXISTS posts;

CREATE TABLE Widgets (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    NumberOfParts INTEGER NOT NULL,
    CreatedDate TIMESTAMP NOT NULL,
    UpdatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
